### PR TITLE
File hierarchy according to Node.js conventions and added Browserify support

### PR DESCRIPTION
**Pull request by piranna**
- Move 'libwebrtc' to 'third_party' folder
- Move 'build.js' to 'bin' folder
- Move Javascript binding files to 'lib' folder
- Changing testing command to standard 'npm test'
- Browserify support and pre-generated file for testing (dist/wrtc.js)
- Clean-up of examples using browser support files
- Removed all not commited files when doing 'make clean'

After all of this, I did a full 'make clean;npm install' and automatically it
downloaded and installed everything successfully, it only keeps to automate the
download and install of the 'depot tools' and the system dependencies.

It also keeps to unify the generation script, currently there is entries at
package.json, Makefile, build.js and binding.gyp, ideally there should be only
the last one as propossed on issue #47.

### CODE REVIEW

**Comment by piranna** [comment]
This also fix issues #9 and #46.

**Comment by modeswitch** [comment]
I moved all the build stuff to `build.js` so `Makefile` is no longer used.

**Comment by piranna** [comment]
Makefile has code to download depot tools that build.js doesn't have, but
knowing this I'll take a look and try to remove it.

Send from my Samsung Galaxy Note II

**Comment by piranna** [comment]
Makefile removed :-)

P.D: 20 minutes compiling libwebrtc with my Dual-Core at 200% CPU usage and a module of 7.5Mb... D'oh! O_o

**Comment by modeswitch** [comment]
Could you convert `bin/clean.sh` into JS? I'd like to avoid adding additional dependencies. Otherwise, looks good and I'll merge.

**Comment by piranna** [comment]
I wouldn't consider myself bash as a "dependency"... :-P but I understand
definitely it would be for Windows. I'll fix it and upload a new commit
with the changes.

2014/1/18 Alan K notifications@github.com

> Could you convert bin/clean.sh into JS? I'd like to avoid adding
> additional dependencies. Otherwise, looks good and I'll merge.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/pull/48#issuecomment-32688268
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
The idea is to eventually support WIndows as well, so running as much as possible in node (which is a hard dependency anyway) is best.

**Comment by piranna** [comment]
Yeah, I got the point ;-) I'm doing it just now, I'll publish the new
commit in some minutes.

2014/1/18 Alan K notifications@github.com

> The idea is to eventually support WIndows as well, so running as much as
> possible in node (which is a hard dependency anyway) is best.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/pull/48#issuecomment-32693150
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
Fixed. I would done this issues with Async.js or directly with Grunt, but
for now it should work, we could revisit it later or directly go for fully
configure the gyp file.

2014/1/18 piranna@gmail.com piranna@gmail.com

> Yeah, I got the point ;-) I'm doing it just now, I'll publish the new
> commit in some minutes.
> 
> 2014/1/18 Alan K notifications@github.com
> 
> > The idea is to eventually support WIndows as well, so running as much as
> > possible in node (which is a hard dependency anyway) is best.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/pull/48#issuecomment-32693150
> > .
> 
> ## 
> 
> "Si quieres viajar alrededor del mundo y ser invitado a hablar en un
> monton de sitios diferentes, simplemente escribe un sistema operativo Unix."
> – Linus Tordvals, creador del sistema operativo Linux

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
Could you be able to publish the changes to NPM?

Send from my Samsung Galaxy Note II

**Comment by modeswitch** [comment]
Yep, I'll do a push there today.

**Comment by piranna** [comment]
Ok, thanks :-)

2014/1/20 Alan K notifications@github.com

> Yep, I'll do a push there today.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/pull/48#issuecomment-32774990
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Pull request merged**
