### PR TITLE
Trigger a null candidate once ice gathering has been completed

### PR DESCRIPTION
**Pull request by DamonOehlman**
This will resolve issue #44

### CODE REVIEW

**Comment by cjb** [comment]
@DamonOehlman Thanks!  I just tested your branch with my own JS and it works great.  Would be awesome to see it this a new wrtc NPM release so I can place a version dependency on it in my code.

**Comment by modeswitch** [comment]
`npm tests` stalls for me at `# monitor the ice connection state of peer:0`. @DamonOehlman can you investigate?

**Comment by cjb** [comment]
That's odd.  It works here with develop HEAD, five times in a row:

```
# monitor the ice connection state of peer:0
ok 67 peer:0 in connected state
# monitor the ice connection state of peer:1
ok 68 peer:1 in connected state
```

**Comment by DamonOehlman** [comment]
I never saw any stalls either, but I will investigate.

**Comment by cjb** [comment]
@modeswitch Hm, any hints for reproducing this?  I tried with network disconnected too, still no stall.

**Comment by cjb** [comment]
@DamonOehlman Any luck reproducing?  Maybe it'd help to hear what kind of platform (OS?) @modeswitch is testing on?  Thanks.

**Comment by modeswitch** [comment]
I'm on Linux here. I haven't had time to debug this yet.

**Comment by modeswitch** [comment]
As a start, here are the dynamic library deps for my compiled `wrtc.node` object:

```
    linux-vdso.so.1 (0x00007fffd936b000)
    libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007fb734cfb000)
    libnss3.so => /usr/lib/libnss3.so (0x00007fb7349bd000)
    libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fb734682000)
    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fb73437d000)
    libm.so.6 => /usr/lib/libm.so.6 (0x00007fb73407c000)
    libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fb733e66000)
    libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fb733c48000)
    libc.so.6 => /usr/lib/libc.so.6 (0x00007fb7338a0000)
    libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007fb73349a000)
    libnssutil3.so => /usr/lib/libnssutil3.so (0x00007fb73326d000)
    libplc4.so => /usr/lib/libplc4.so (0x00007fb733068000)
    libplds4.so => /usr/lib/libplds4.so (0x00007fb732e64000)
    libnspr4.so => /usr/lib/libnspr4.so (0x00007fb732c25000)
    libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fb732a05000)
    libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fb732801000)
    /usr/lib64/ld-linux-x86-64.so.2 (0x00007fb7357ce000)
    libz.so.1 => /usr/lib/libz.so.1 (0x00007fb7325ea000)
    librt.so.1 => /usr/lib/librt.so.1 (0x00007fb7323e2000)
    libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fb7321dd000)
    libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fb731fd7000)

```

Can we compare lists and see if maybe it's an issue with one of my system libraries?

**Comment by cjb** [comment]
@modeswitch Thanks, here's mine, 64-bit Ubuntu 14.04.  It seems like it would be an unlikely cause, right?  @DamonOehlman's changes were purely to `peerconnection.js`.  If you add a console.log() to lib/peerconnection.js:123 (inside `pc.onicegatheringstatechange`) does it fire?  That should help us work out whether you're missing onicegatheringstatechanges for some reason, or that the (pure JS) callback chain isn't working for you.

```
    linux-vdso.so.1 =>  (0x00007fffd39fe000)
    libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f56d4b80000)
    libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007f56d4847000)
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f56d4511000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f56d420d000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f56d3f07000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f56d3cf0000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f56d3ad2000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f56d370c000)
    libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f56d3331000)
    libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007f56d3106000)
    libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007f56d2f01000)
    libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007f56d2cfc000)
    libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007f56d2abf000)
    libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f56d28a0000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f56d269b000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f56d5635000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f56d2493000)
    libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f56d228e000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f56d2088000)
```

**Comment by cjb** [comment]
Here's my test runner output on a fresh git clone, I see the test count is higher than yours.  Do you get some candidates gathered before the hang?

```
> wrtc@0.0.20 test /home/cjb/git/node-webrtc
> node test/all.js

TAP version 13
# create a peer connection
ok 1 created
# createOffer function implemented
ok 2 implemented
# can call createOffer
ok 3 createOffer succeeded
ok 4 type === offer
ok 5 got sdp
# setLocalDescription function implemented
ok 6 implemented
# can call setLocalDescription
ok 7 local description set
ok 8 we have local sdp
# TODO: cleanup connection
ok 9 connection closed
# create a peer connection
ok 10 created
# createOffer
ok 11 createOffer succeeded
ok 12 type === offer
ok 13 got sdp
# setLocalDescription with a created RTCSessionDescription
ok 14 local description set
ok 15 we have local sdp
# TODO: cleanup connection
ok 16 connection closed
# create the peer connections
ok 17 peer:0 created ok
ok 18 peer:1 created ok
# peers are created and in the expected connection state
ok 19 should be equal
ok 20 should be equal
# create a datachannel on peer:0
ok 21 (unnamed assert)
ok 22 created with correct label
# createOffer for peer:0
ok 23 createOffer succeeded
ok 24 type === offer
ok 25 got sdp
# setLocalDescription for peer:0
ok 26 ok
# capture ice candidates for peer:0
{...candidates...}
ok 27 have candidates for peer:0
# setRemoteDescription for peer:1
ok 28 ok
# provide peer:1 with the peer:0 gathered ice candidates
ok 29 added candidate
ok 30 added candidate
ok 31 added candidate
ok 32 added candidate
ok 33 added candidate
ok 34 added candidate
ok 35 added candidate
ok 36 added candidate
ok 37 added candidate
ok 38 added candidate
ok 39 added candidate
ok 40 added candidate
ok 41 added candidate
ok 42 added candidate
ok 43 added candidate
ok 44 added candidate
ok 45 added candidate
ok 46 added candidate
ok 47 added candidate
ok 48 added candidate
ok 49 added candidate
ok 50 added candidate
ok 51 added candidate
ok 52 added candidate
# createAnswer for peer:1
ok 53 createOffer succeeded
ok 54 type === answer
ok 55 got sdp
# setLocalDescription for peer:1
ok 56 ok
# capture ice candidates for peer:1
{...candidates...}
ok 57 have candidates for peer:1
# setRemoteDescription for peer:0
ok 58 ok
# provide peer:0 with the peer:1 gathered ice candidates
ok 59 added candidate
ok 60 added candidate
ok 61 added candidate
ok 62 added candidate
ok 63 added candidate
ok 64 added candidate
ok 65 added candidate
ok 66 added candidate
ok 67 added candidate
ok 68 added candidate
ok 69 added candidate
ok 70 added candidate
# peer:1 triggers data channel event
WARNING: no real random source present!
ok 71 got data channel
ok 72 data channel has correct label
# monitor the ice connection state of peer:0
ok 73 peer:0 in connected state
# monitor the ice connection state of peer:1
ok 74 peer:1 in connected state
# data channel connectivity
ok 75 successfully called send on dc:0
ok 76 got valid data
ok 77 two bytes sent
ok 78 byte:0 matches expected
ok 79 byte:1 matches expected
# close the connections
ok 80 closed connections

1..80
# tests 80
# pass  80

# ok
```

**Comment by cjb** [comment]
@modeswitch Please could you tell us which Linux distribution/release you're running?  I'll spin up a VM of whatever it is and try to reproduce that way.  I tested the new wrtc release and all tests still pass here.

**Comment by cjb** [comment]
Okay, I installed the latest Arch (2014.06.01) and can reproduce this there.  Hanging after `# monitor the ice connection state of peer:0`, with a text spinner on the console.  Interestingly, my app which depends on the new onicecandidate behavior works fine, so it's not a simple form of breakage.

Ah, I hit ^Z early on in the tests to attach strace (with `strace -p`) and then the tests passed when I resumed `npm test` with `fg`!  But running it directly under strace still hangs.

So it's a very weird kind of race condition, possibly only affecting processes that try to use webrtc very soon after launch?

**Comment by cjb** [comment]
@modeswitch @DamonOehlman This patch fixes Arch, causes all tests to pass:

```
diff --git a/test/connect.js b/test/connect.js
index a60fd07..4df68a3 100644
--- a/test/connect.js
+++ b/test/connect.js
@@ -159,7 +159,8 @@ test('monitor the ice connection state of peer:0', function(t) {
   t.plan(1);

   function checkState() {
-    if (peers[0].iceConnectionState === 'connected') {
+    if (peers[0].iceConnectionState === 'connected' ||
+        peers[0].iceConnectionState === 'completed') {
       t.pass('peer:0 in connected state');
       peers[0].oniceconnectionstatechange = null;
     }
```

The hang happens because we're waiting for iceConnectionState to change to "connected", but the completion callback for oniceconnectionstatechange has already fired and put us in "completed".  I think "completed" is **after** "connected" in the state diagram?  In which case, it's a race condition checking for an earlier stage than the final one, and perhaps my patch above is doing the right thing.  What do you think?

**Comment by cjb** [comment]
Possibly relevant Chrome bug: https://code.google.com/p/chromium/issues/detail?id=371799

The submitter used the same workaround I suggested above.

**Comment by DamonOehlman** [comment]
Nice pickup @cjb!

**Comment by modeswitch** [comment]
I'm also only getting 54 tests passed. @cjb how many do you see on your arch setup?

**Comment by cjb** [comment]
54 here too, but my Arch setup has one interface (fake wired ethernet for the VM) and my Ubuntu host has three (wired, wifi ipv4, wifi ipv6), so I think the difference is purely that more local candidates exist on the Ubuntu host.

**Pull request merged**
