### PR TITLE
Node.js 10

### PR DESCRIPTION
**Pull request by nazar-pc**
First set of changes needed for Node.js 10 as suggested in #399

Compiles without errors (lots of warnings).

Most of tests are fine, stops at this:
```
ok 145 the audio RTCRtpReceiver's .track has .readyState "live"
ok 146 the video RTCRtpReceiver's .track has .readyState "live"

Thread 1 "node" received signal SIGSEGV, Segmentation fault.
0x00007ffff7711f23 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) backtrace
#0  0x00007ffff7711f23 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007fffe7424564 in node_webrtc::RTCRtpReceiver::GetParameters(Nan::FunctionCallbackInfo<v8::Value> const&) () from /web/github/node-webrtc/build/Release/wrtc.node
#2  0x00007fffe7420f0c in Nan::imp::FunctionCallbackWrapper () from /web/github/node-webrtc/build/Release/wrtc.node
#3  0x0000000000a78aaa in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) ()
#4  0x0000000000ad62fa in ?? ()
#5  0x0000000000ad6b09 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
#6  0x000039318490427d in ?? ()
#7  0x00003931849041c1 in ?? ()
#8  0x00007fffffff9550 in ?? ()
#9  0x0000000000000006 in ?? ()
#10 0x00007fffffff95e8 in ?? ()
#11 0x00003931849144f7 in ?? ()
#12 0x000034aa2d8022e1 in ?? ()
#13 0x0000298796bef371 in ?? ()
#14 0x0000000500000000 in ?? ()
#15 0x000034aa2d802321 in ?? ()
#16 0x000023e860929059 in ?? ()
#17 0x000016ab5b6bb239 in ?? ()
#18 0x000023e860929059 in ?? ()
#19 0x0000298796bef371 in ?? ()
#20 0x000003bbd0514219 in ?? ()
#21 0x00002da9e7fa3141 in ?? ()
#22 0x000000a300000000 in ?? ()
#23 0x000016ab5b6bbab1 in ?? ()
#24 0x000023e860928ac9 in ?? ()
```

### CODE REVIEW

**Comment by markandrus** [comment]
@nazar-pc awesome! Re: the `std::string` issue, in my experience this has typically occurred when using gcc newer than 4.8 or not setting the `-D_GLIBCXX_USE_CXX11_ABI=0`. Let us see what CI says about the changes.

**Comment by markandrus** [comment]
@nazar-pc PR is failing on Travis CI due to this:

```
You must run make format before submitting a pull request
```

Can you do

```
(cd build; make format)
```

then commit the formatted source?

Appveyor doesn't check formatting, and it's green there 👍

**Comment by nazar-pc** [comment]
I'm on GCC 7.3.0, this is probably why. Pushed fixed commit.

**Comment by markandrus** [comment]
> I'm on GCC 7.3.0, this is probably why. Pushed fixed commit.

Weird that it does that... thanks for fixing the commit, though. All green! 👍

**Pull request merged**
