### PR TITLE
Initial (totally borked commit, I'm sure, but hey, it compiles!) commit of FileMedia object.

### PR DESCRIPTION
**Pull request by JessieAMorris**
This contains the beginnings of the FileMedia object. With this, it should be theoretically possible to record some media and play it back.

Things to do in it:

I'm not using talk_base::scoped_refptr because most of the cricket namespaced objects don't have Release or other such functions.

Thoughts, comments, telling me why this is terrible and I should never do C++ again, etc. would be great.

### CODE REVIEW

**Comment by modeswitch** [comment]
@JessieAMorris I haven't had time to review this yet, but I haven't forgotten about it. I'll add some feedback when I get home next week.

**Comment by markandrus** [comment]
@JessieAMorris Wondering what the state of this is? I was unable to compile on OS X.

First I was getting

```
../src/filemedia.cc:161:38: error: expected a class or namespace
  MediaStream* mediastream = webrtc::MediaStream::Create(label);
                             ~~~~~~~~^
```

After adding some header(s), I got a conversion error regarding `scoped_refptr`.

```
../src/filemedia.cc:161:16: error: no viable conversion from 'talk_base::scoped_refptr<MediaStream>' to 'MediaStream *'
  MediaStream* mediastream = webrtc::MediaStream::Create(label);
               ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Haven't had an opportunity to dig deeper yet.

Also, since you asked for comments ;-)  do you mind pushing a new commit that removes the following?
- CMakeLists.txt
- main.cpp
- wrtc.cbp
- wrtc.kdev4

**Comment by JessieAMorris** [comment]
I never had it working on OSX, only on Debian ATM.

And yes, I can kill those files. My bad. :-|
-- 
Jessie A. Morris

On March 3, 2014 at 19:40:17, Mark Roberts (notifications@github.com) wrote:

@JessieAMorris Wondering what the state of this is? I was unable to compile on OS X.

First I was getting

../src/filemedia.cc:161:38: error: expected a class or namespace
  MediaStream\* mediastream = webrtc::MediaStream::Create(label);
                             ~~~~~~~~^

After adding some header(s), I got a conversion error regarding scoped_refptr.

../src/filemedia.cc:161:16: error: no viable conversion from 'talk_base::scoped_refptr<MediaStream>' to 'MediaStream _'
  MediaStream_ mediastream = webrtc::MediaStream::Create(label);
               ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Haven't had an opportunity to dig deeper yet.

Also, since you asked for comments ;-) do you mind pushing a new commit that removes the following?

CMakeLists.txt
main.cpp
wrtc.cbp
wrtc.kdev4
—
Reply to this email directly or view it on GitHub.

**Comment by markandrus** [comment]
I was able to resolve the conversion issue:

``` diff
$ git diff JessieAMorris/develop HEAD src/filemedia.cc
diff --git a/src/filemedia.cc b/src/filemedia.cc
index 0764cb7..d2d7c93 100644
--- a/src/filemedia.cc
+++ b/src/filemedia.cc
@@ -4,6 +4,7 @@
 #include <iostream>
 #include <string>

+#include "talk/app/webrtc/mediastream.h"
 #include "talk/app/webrtc/jsep.h"
 #include "webrtc/system_wrappers/interface/ref_count.h"

@@ -158,7 +159,7 @@ NAN_METHOD(FileMedia::createStream) {
   v8::String::Utf8Value tmp(args[0]->ToString());
   std::string label = *tmp;

-  MediaStream* mediastream = webrtc::MediaStream::Create(label);
+  webrtc::MediaStream* mediastream = webrtc::MediaStream::Create(label);

   v8::Local<v8::Value> cargv[1];
   cargv[0] = v8::External::New(static_cast<void*>(mediastream));
```

And now I'm testing with the following script:

``` js
var wrtc = require('./lib/index'),
    fm = new wrtc.FileMedia({
      voiceInput: 'stereo_pcmu.rtp'
    }),
    chan = fm.createChannel(),
    ms = new wrtc.RTCMediaStream('stereo_pcmu'),
    pc = new wrtc.RTCPeerConnection();
pc.addStream(ms);
```

But `addStream` fails:

```
> pc.addStream(ms);
-> TRACE: Call::static v8::Handle<v8::Value> PeerConnection::AddStream(const v8::Arguments &)
Assertion failed: (handle->InternalFieldCount() > 0), function Unwrap, file /Users/mroberts/.node-gyp/0.10.26/src/node_object_wrap.h, line 61.
[1]    57417 abort      node
```

**Comment by modeswitch** [comment]
@markandrus I'm happy to merge some good tests for the mediastream API.

**Comment by modeswitch** [comment]
Native backend won't support media streams at this time.

**Pull request closed without merging**
