### PR TITLE
Accessing to module namespace instead of Javascript files

### PR DESCRIPTION
**Pull request by piranna**
As suggested at https://groups.google.com/d/msg/nodejs/RGU0AwTm8cU/Y9y1GppJjA4J

This prevents to have in the future issues like the #77

### CODE REVIEW

**Comment by piranna** [comment]
It has been added the changes for my proposal on issue #80 on this pull-request, I should have move it to a diferent feature branch, sorry. I can do it if required.

Here you have an example of my proposal to unify internal and public classes, in this case done with the PeerConnection one. As a result of it, not only the code is almost 100 lines smaller and gets simpler and cleaner and more easier to maintain and expand (adding EventTarget events will be trivial), but also it will waste less memory and there are no private attributes accesibles from outside, making it more secure and standard compliant. I have updated the methods parameters names to the current ones on the specification. For the native PeerConnection events onicecandidate and ondatachannel I needed to remove the function names due to conflicts that provocated an infinite recursion, but this will be fixed when EventTarget events get implemented.

Opinions? Comments? Suggestions? If you agree, I can keep working on adding the EventTarget events on this and apply the same code scheme to the other public classes.

**Comment by modeswitch** [comment]
Can you split this pull into two?

**Comment by piranna** [comment]
I'll

**Comment by piranna** [comment]
I'll try it.

**Comment by piranna** [comment]
Commits splitted :-) This is what happens when you can't sleep... :-P

**Comment by wouldgo** [comment]
@piranna & @modeswitch: if this PR and the related one are eligible for merging I'll lint the js file after the merging.

**Comment by piranna** [comment]
+1, although I put the extra espaces just for clearance...

**Pull request merged**
