### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by markandrus**
@modeswitch would you consider the following changes?
1. [Commit 1](https://github.com/js-platform/node-webrtc/commit/60212a0592b74b7b9ef2fb39d28404283a6dfd25) completely removes MediaStream and MediaStreamTrack; I would like to investigate adding these back in a separate PR.
2. [Commit 2](https://github.com/js-platform/node-webrtc/commit/6c5a39d8cd2f565213c66198b5a8dbea207df909) quashes some compiler warnings by removing unused variables.
3. [Commit 3](https://github.com/js-platform/node-webrtc/commit/ea3015e569926ec08d3d5ce95a2a705fd7f54f53), following [Google's C++ style guide](https://google.github.io/styleguide/cppguide.html) and [cpplint.py](https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py),
   - Reorders includes according to
     https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
   - Removes `using namespace` declarations from .h files
   - Converts `using namespace` declarations to individual `using` declarations in .cc files where v8-namespaced symbols are commonly used
   - Adds or updates header guards and closing namespace comments according to cpplint.py suggestions
   
   Additionally, I ran [include-what-you-use](http://include-what-you-use.org/) on the project
   
   ```
   CXX="iwyu -Xiwyu --mapping_file=../node-webrtc.imp" make -C build -k
   ```
   
   with the following mapping, node-webrtc.imp,
   
   ``` json
   [
     { "include": [ "@<_types/_int.*>", "private", "<stdint.h>", "public" ] },
     { "include": [ "@<_types/_uint.*>", "private", "<stdint.h>", "public" ] },
     { "include": [ "@\"nan_.*\"", "private", "\"nan.h\"", "public" ] },
     { "include": [ "\"node_version.h\"", "private", "\"nan.h\"", "public" ] },
     { "include": [ "\"uv-unix.h\"", "private", "\"uv.h\"", "public" ] },
   ]
   ```
   
   and applied its suggestions (namely bringing in dependencies such as string and stdint.h explicity).
4. [Commit 4](https://github.com/js-platform/node-webrtc/commit/039a192792168311cdd5c3d4bd9db23b74b775d3) applies some additional cpplint.py suggestions:
   - Updates indentation, whitespace, braces, etc.
   - Changes C-style casts to reinterpret_cast, static_cast, const_cast, etc.
   - Replaces remaining uses of NULL with nullptr
   
   I ignored some of the cpplint.py suggestions, including
   - build/include
   - legal/copyright
   - whitespace/line_length
5. [Commit 5](https://github.com/js-platform/node-webrtc/commit/20d15ffc9255d576436ba35c5a44096e07b4fa18) removes extra `Nan::HandleScope`s from `NAN_METHOD`, `NAN_GETTER`, etc., methods, since a scope is already implicit.

### CODE REVIEW

**Comment by markandrus** [comment]
I realize Commit 4 is mostly aesthetics, but as the project now includes a mix of whitespace and brace styles, I thought it may make sense to land on a single style. Since this project includes WebRTC sources, I thought it might make sense to use the Google C++ style guide. What do you think?

**Comment by markandrus** [comment]
Docker images with `TRAVIS_NODE_VERSION`s 4 and 5 are passing, but 0.10 and 0.12 are failing with

```
warning: identifier 'nullptr' is a keyword in C++11 [-Wc++0x-compat]
```

Can we not use C++11 features in 0.10 and 0.12? Any idea where this flag is getting set?

**Comment by modeswitch** [comment]
Nice work!

This will take me a little while to review, given the extent of the changes.

Go ahead and use Google C++ style everywhere.

Not sure why you're getting failures in 0.10 and 0.12.

**Comment by markandrus** [comment]
Thanks @modeswitch! Also, setting `-std=c++11` solved the build failures.

**Pull request merged**
