### PR TITLE
Use epoll-enabled PhysicalSocketServer on Linux

### PR DESCRIPTION
**Pull request by markandrus**
There may be important patches we're missing. I just copied the epoll-enabled PhysicalSocketServer from the WebRTC Issue. Needs testing.

~~**Edit:** getting crashes on Linux.~~ ~~Nevermind, I didn't set `CXX`/`CC` correctly. Seems to work?~~

**Edit 2:** Still need to define `WEBRTC_LINUX`.

---

PTAL @nazar-pc

### CODE REVIEW

**Comment by nazar-pc** [comment]
Can't compile for some reason on Ubuntu 14.04. Upgraded Cmake from 3.2 to 3.11 (`FILTER` was not supported), but still getting error for some reason:
```
...
-- Downloading: https://nodejs.org/download/release/v9.10.1/SHASUMS256.txt
CMake Error at NodeJS.cmake:293 (message):
  Unable to extract header archive checksum
Call Stack (most recent call first):
  CMakeLists.txt:12 (nodejs_init)
...
```

UPD: Error is caused by bad libcurl, trying to resolve it

**Comment by markandrus** [comment]
Sorry, @nazar-pc -- I'll have a fix for that shortly.

**Comment by markandrus** [comment]
OK, I've pushed a change, and now

* The script I shared in #362 can scale up to 3000 RTCPeerConnections (much higher and I hit the thread limit on my Linux machine).
* The script I shared in #340 can scale up to 1500 RTCPeerConnection pairs (although it gets quite slow!).

**Comment by nazar-pc** [comment]
Doesn't crash anymore 👍

**Comment by markandrus** [comment]
M61 has the `epoll` code merged. So, once we can update libwebrtc from M60 to something newer, we can drop these extra files.

**Comment by markandrus** [comment]
@nazar-pc is this OK to release from your perspective?

**Comment by nazar-pc** [comment]
Absolutely!

**Pull request merged**
