### PR TITLE
Specify lack of Apple Silicon support

### PR DESCRIPTION
**Pull request by QuixThe2nd**
It has been 4 years since the last Intel mac has been released, so a large proportion of Mac users are using Apple Silicon macs.

Many developers have attempted to install this library on Apple Silicon and were unable to install. It should be made clear that Apple Silicon Macs aren't supported.

This can be seen by looking at the countless issues opened relating to this: #764 #760 #749 #729 #725 #718 #698 #695 #693 #680

P.s. I am happy to help contribute to whatever is needed to getting this working on Apple Silicon, just tell me what needs to be done.

### CODE REVIEW

**Comment by Neptune1190** [comment]
Agreed,This is heavily annoying when trying to maintain a project,and cant due to the library not supporting the modern hardware

**Comment by duvallj** [comment]
Hi @QuixThe2nd ,

Yeah it's a good idea to update this page to make it clear this library does not support Apple Silicon. I'm currently maintaining the [`@roamhq/wrtc`](https://github.com/WonderInventions/wrtc) fork which does have support for Apple Silicon, but is a bit less battle-tested than this library. Thanks for the PR!

**Comment by QuixThe2nd** [comment]
Hi @duvallj,
Thank you for the merge! Please let me know what I can do to expedite progress on your fork. Would love to see it merged to this repo.

**Comment by rubbishCoder** [comment]
Hi @QuixThe2nd @duvallj,

 I am still facing issue in installing it to Mac with arm64. I tried to add the repo url to package.json and was not able to install the latest code in develop branch. Is that the right way?? 

Because I don't see any release after the fix was merged. Please let me know what's the right way to add the latest arm64 support to my code.

**Comment by duvallj** [comment]
Hi @rubbishCoder,

This repository does not have arm64 support. You'll want to use the [`@roamhq/wrtc`](https://github.com/WonderInventions/node-webrtc) package instead for that. Please open an issue on that repository if you have troubles with that.

**Comment by Moe03** [comment]
> Hi @QuixThe2nd ,
> 
> Yeah it's a good idea to update this page to make it clear this library does not support Apple Silicon. I'm currently maintaining the [`@roamhq/wrtc`](https://github.com/WonderInventions/wrtc) fork which does have support for Apple Silicon, but is a bit less battle-tested than this library. Thanks for the PR!

This package is a life saver thank you! complete replacement for wrtc base package working fine for me on M3 macbook, note for everyone btw I've tried to use the other @koush/wrtc package and that didn't work for me but this package did: @roamhq/wrtc

**Pull request merged**
