### PR TITLE
Update to WebRTC M81

### PR DESCRIPTION
**Pull request by markandrus**
See #620&hellip;

### CODE REVIEW

**Comment by nick-erm** [comment]
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 6.1.7601.
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
Compile Errors:

..\node-webrtc\src\dictionaries\webrtc\rtp_encoding_parameters.cc(52): error C2039: **'codec_payload_type'**: is not a member of 'webrt
c::RtpEncodingParameters' [..\node-webrtc\build\wrtc.vcxproj]
..\node-webrtc\build\external\libwebrtc\download\webrtc/api/rtp_parameters.h(408): note: see declaration of 'webrtc::RtpEncodingP
arameters'
..\node-webrtc\src\dictionaries\webrtc\rtp_encoding_parameters.cc(55): error C2039: '**dtx**': is not a member of 'webrtc::RtpEncodingP
arameters' [..\node-webrtc\build\wrtc.vcxproj]
..\node-webrtc\build\external\libwebrtc\download\webrtc/api/rtp_parameters.h(408): note: see declaration of 'webrtc::RtpEncodingP
arameters'
..\node-webrtc\src\dictionaries\webrtc\rtp_encoding_parameters.cc(64): error C2039: '**ptime**': is not a member of 'webrtc::RtpEncodin
gParameters' [..\node-webrtc\build\wrtc.vcxproj]
..\node-webrtc\build\external\libwebrtc\download\webrtc/api/rtp_parameters.h(408): note: see declaration of 'webrtc::RtpEncodingP
arameters'

FIXED by change rtp_encoding_parameters.cc.

**Comment by nick-erm** [comment]
But can't fixed this errors:
('Convert': is not a member of 'node_webrtc::Converter<S,T>';
'Convert': identifier not found)...

..\node-webrtc\src/converters.h(80): error C2039: 'Convert': is not a member of 'node_webrtc::Converter<S,T>' [..\node-we
brtc\build\wrtc.vcxproj]
          with
          [
              S=std::pair<Napi::Env,absl::optional<webrtc::DegradationPreference>>,
              T=Napi::Value
          ]
  ..\node-webrtc\src/converters.h(80): note: see declaration of 'node_webrtc::Converter<S,T>'
          with
          [
              S=std::pair<Napi::Env,absl::optional<webrtc::DegradationPreference>>,
              T=Napi::Value
          ]
  ..\node-webrtc\src/dictionaries/macros/napi.h(39): note: see reference to function template instantiation 'node_webrtc::Validatio
n<Napi::Value> node_webrtc::From<Napi::Value,std::pair<Napi::Env,absl::optional<webrtc::DegradationPreference>>>(const S)' being compiled
          with
          [
              S=std::pair<Napi::Env,absl::optional<webrtc::DegradationPreference>>
          ]
  ..\node-webrtc\src\dictionaries\webrtc\rtp_parameters.cc(31): note: see reference to function template instantiation 'node_webrtc
::Maybe<node_webrtc::Errors> node_webrtc::ConvertAndSet<absl::optional<webrtc::DegradationPreference>>(const Napi::Env,Napi::Object,const std
::string &,T)' being compiled
          with
          [
              T=absl::optional<webrtc::DegradationPreference>
          ]
..\node-webrtc\src/converters.h(80): error C3861: 'Convert': identifier not found [..\node-webrtc\build\wrtc.vcxproj]

**Comment by nick-erm** [comment]
**Hello, markandrus !** 
After some trouble's, I be able successfully compile wrtc module.
Config: OS: Win64; Node v13.14.0; WRTC v0.4.4; Windows SDK v10.0.18362.0; MSVC 19.25.28614.0; is_clang=false;
depot_tools - last master version with Python v3; Google src - last master version;

Trouble's below...
May be this information be helpful.

Change rtp_encoding_parameters.cc - remove deprecated parameters: 'codec_payload_type', 'dtx', 'ptime'.

In rtp_parameters.cc(31)
 => throw (difficult (needing much effort or skill to accomplish, deal with, or understand ;-)) for me) compile errors in 
 _(31)NODE_WEBRTC_CONVERT_AND_SET_OR_RETURN(env, object, "degradationPreference", parameters.degradation_preference):
..node-webrtc\src/converters.h(80,27): error C2039: 'Convert': is not a member of 'node_webrtc::Converter<S,T>' [..node
-webrtc\build\wrtc.vcxproj]
          with
          [
              S=std::pair<Napi::Env,absl::optional<webrtc::DegradationPreference>>,
              T=Napi::Value
          ]
..node-webrtc\src/converters.h(80): message : see declaration of 'node_webrtc::Converter<S,T>' [..node-webrtc\build\wrt
c.vcxproj]
          with
          [
              S=std::pair<Napi::Env,absl::optional<webrtc::DegradationPreference>>,
              T=Napi::Value
          ]
..node-webrtc\src/dictionaries/macros/napi.h(39): message : see reference to function template instantiation 'node_webrtc::Validat
ion<Napi::Value> node_webrtc::From<Napi::Value,std::pair<Napi::Env,absl::optional<webrtc::DegradationPreference>>>(const S)' being compiled [
..node-webrtc\build\wrtc.vcxproj]
          with
          [
              S=std::pair<Napi::Env,absl::optional<webrtc::DegradationPreference>>
          ]
..node-webrtc\src\dictionaries\webrtc\rtp_parameters.cc(31): message : see reference to function template instantiation 'node_webr
tc::Maybe<node_webrtc::Errors> node_webrtc::ConvertAndSet<absl::optional<webrtc::DegradationPreference>>(const Napi::Env,Napi::Object,const s
td::string &,T)' being compiled [..node-webrtc\build\wrtc.vcxproj]
          with
          [
              T=absl::optional<webrtc::DegradationPreference>
          ]
..node-webrtc\src/converters.h(80,1): error C3861: 'Convert': identifier not found [..node-webrtc\build\wrtc.vcxproj]_


Next warnings may except other compilation errors:
_..node-webrtc\src\node\error_factory.cc(79): warning C4715: 'node_webrtc::ErrorFactory::DOMExceptionNameToString': not all control
 paths return a value_

In: error_factory.cc =>
_const char* node_webrtc::ErrorFactory::DOMExceptionNameToString(DOMExceptionName name) {
  switch (name) {_
  
 => need added default case.
In this case switch may not return value.
 
Also: impls.h !!! =>
_CONVERTER_IMPL(ENUM(), std::string, value) {
  switch (value) {
      ENUM(_LIST)
  }
}_

Also: some_error.cc =>
_TO_NAPI_IMPL(SomeError, pair) {_

Two switch case without default case, as result - may not return value.

Security and memory problem with using getenv:
(https://stackoverflow.com/questions/48568707/getenv-function-may-be-unsafe-really)
_..node-webrtc\src\dictionaries\webrtc\rtc_configuration.cc(18,33): warning C4996: 'getenv': This function or variable may be unsaf
e. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details._


Type conversion warnings:
_..node-webrtc\src\webrtc\test_audio_device_module.cc(59): warning C4244: 'initializing': conversion from 'float' to 'const int64_t
', possible loss of data

..node-webrtc\src\webrtc\test_audio_device_module.cc(225): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible
 loss of data_

and in 
_rtp_codec_capability.cc, rtp_encoding_parameters.cc_

and napi.cc
_napi.cc(111,62): warning C4244: 'argument': conversion from '_Ty2' to 'double', possible loss of data._


I'm added #include <winsock2.h> in NodeJS.cmake:
    _file(APPEND ${OUTPUT} "#ifndef WIN32_LEAN_AND_MEAN\n")
    file(APPEND ${OUTPUT} "#define WIN32_LEAN_AND_MEAN\n")
    file(APPEND ${OUTPUT} "#endif\n")
    file(APPEND ${OUTPUT} "\n")
    file(APPEND ${OUTPUT} "#include <windows.h>\n")
	file(APPEND ${OUTPUT} "#include <winsock2.h>\n")_

,as recommended on StackOverflow:
Alternatively define WIN32_LEAN_AND_MEAN first:
// Don't include additional header files from windows.h
// These must be then included explicitly
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <winsock2.h>
// Include other header files here 

but not solve: warning C4005: '_WINSOCKAPI_': macro redefinition.

And add #pragma warning (disable: 4003) in _impls.h, def.h, decls.h._

**Comment by markandrus** [comment]
@nick-erm amazing! any chance you could open a PR against this branch?

**Comment by nick-erm** [comment]
> 
> 
> @nick-erm amazing! any chance you could open a PR against this branch?

I'm ready. But havn't rights to create PR in this brunch. May create new Issue with check list.

**Pull request merged**
