### PR TITLE
Restructured js "proxies" into separate objects

### PR DESCRIPTION
**Pull request by DamonOehlman**
Ok, this one is definitely a matter of opinion, but I'd recommend moving your `peerconnection.js` file from the `src/` directory and separating it out into files at the top level of your project that encapsulate just one class.  When writing modules for a node environment, this is certainly my preferred approach and that of quite a few other module authors also.  It is completely up to you though.

Since @raynos commented on the tape question, I've cced him in for comment here also.

Cheers,
Damon.

### CODE REVIEW

**Comment by Raynos** [comment]
:+1: for top level files & 1 class / function per file.

But it's kind of opinionated.

**Comment by modeswitch** [comment]
Merged! But I might move the JS files into a subdirectory at some point for tidiness.

**Comment by DamonOehlman** [comment]
Absolutely - whatever you decide.  I remember someone wrote a really great post on the benefits of putting libraries at a top level to make it easier for users of your module to cherry-pick the functionality they want (e.g. `require('webrtc/peerconnection')`.

I thought it was @isaacs but I've had a look around and couldn't find it :/

**Comment by Raynos** [comment]
thats the reason i put my modules in the root directory. So I can import them one class / function at a time.

**Comment by modeswitch** [comment]
Yeah, that could be nice for later when there's audio/video support.

**Comment by piranna** [comment]
On npm documentation it recommends to set the package .js files inside a
lib/ folder instead of the root folder (as I used to do before to read it)
so the root folder gets cleaner, and point it out on the package.json file.

2013/10/21 Alan K notifications@github.com

> Yeah, that could be nice for later when there's audio/video support.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/pull/18#issuecomment-26692826
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by DamonOehlman** [comment]
@piranna I've just revisited the [package.json](https://npmjs.org/doc/json.html) documentation to see if this is mentioned anywhere, but I couldn't find any reference.

Can you please drop a link to the documentation you are referring to please.  I know that this is one way people do structure modules, but can't find where this is recommended practice.

**Comment by piranna** [comment]
It's not a hard requeriment, but seems it's recommended. I extrapolated it
from https://npmjs.org/doc/json.html#directories-lib and
http://wiki.commonjs.org/wiki/Packages/1.0#Optional_Fields

2013/10/21 Damon Oehlman notifications@github.com

> @piranna https://github.com/piranna I've just revisited the package.jsonhttps://npmjs.org/doc/json.htmldocumentation to see if this is mentioned anywhere, but I couldn't find any
> reference.
> 
> Can you please drop a link to the documentation you are referring to
> please. I know that this is one way people do structure modules, but can't
> find where this is recommended practice.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/modeswitch/node-webrtc/pull/18#issuecomment-26706539
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Pull request merged**
