### PR TITLE
fix race during close

### PR DESCRIPTION
**Pull request by sudison**
It's related to issue: https://github.com/js-platform/node-webrtc/issues/358

### CODE REVIEW

**Comment by markandrus** [comment]
Thank you for this, @sudison. Is there any chance you could add a test demonstrating the issue that fails before your change and is resolved by your change? That would ensure we do not regress here.

**Comment by sudison** [comment]
It's a race condition, may not be able to write test cases to reproduce the issue easily.

**Comment by markandrus** [comment]
@sudison OK, I am still trying to understand the change then. From looking at the excerpts below, the JavaScript changes should be no different than what we had before (since `this.readyState` is just a getter for `internalDC.readyState`) _unless_ it is the case that HandleStateEvent can be called with a state that does not match the underlying `_jingleDataChannel->state()`? i.e., `this.readyState` is still "open" but we got an `event` that says "closed"? Does this hypothesis make sense and is it the one you were working under?

Thinking some more, I do like this change, because my goal is that we can eventually remove the JavaScript layer. Therefore, the C++ RTCDataChannel should only define APIs in the WebRTC spec. So eventually, I'd like `internalDC.onstatechange` to be removed, and we just surface `onopen` and `onclose`, per [the spec](https://w3c.github.io/webrtc-pc/#rtcdatachannel).

**datachannel.js**

```js
-  internalDC.onstatechange = function onstatechange() {
-    switch (this.readyState) {
+  internalDC.onstatechange = function onstatechange(data) {
+    switch (data) {
       case 'open':
         self.dispatchEvent({ type: 'open' });
         break;
       case 'closed':
         self.dispatchEvent({ type: 'close' });
         break;
     }
   };
```

```js
// ...
    readyState: {
      get: function getReadyState() {
        return internalDC.readyState;
      }
    },
// ...
```

**datachannel.cc**

```diff
 void DataChannel::HandleStateEvent(const DataChannelStateChangeEvent& event) {
   TRACE_CALL;
   Nan::HandleScope scope;
-  MakeCallback("onstatechange", 0, nullptr);
+  Local<Value> argv[1];
+  if (event.state == webrtc::DataChannelInterface::kClosed) {
+    argv[0] = Nan::New("closed").ToLocalChecked();
+  } else {
+    argv[0] = Nan::New("open").ToLocalChecked();
+  }
+  
+  MakeCallback("onstatechange", 1, argv);
   if (event.state == webrtc::DataChannelInterface::kClosed) {
     Stop();
   }
   TRACE_END;
 }
```

```cpp
NAN_GETTER(DataChannel::GetReadyState) {
  TRACE_CALL;
  (void) property;

  auto self = AsyncObjectWrapWithLoop<DataChannel>::Unwrap(info.Holder());

  CONVERT_OR_THROW_AND_RETURN(self->_jingleDataChannel
      ? self->_jingleDataChannel->state()
      : webrtc::DataChannelInterface::kClosed,
      state,
      Local<Value>);

  TRACE_END;
  info.GetReturnValue().Set(state);
}
```

**Comment by sudison** [comment]
Yes, we are on the same page about the race condition in GetReadyState.

**Comment by markandrus** [comment]
OK, thanks @sudison 👍

**Comment by markandrus** [comment]
Do you mind running `make format`? That should cause Travis to pass. Then we can merge.

**Pull request merged**
